name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Check Xcode version
        run: |
          xcodebuild -version
          XCODE_VER=$(xcodebuild -version | grep Xcode | awk '{print $2}')
          if [[ "${XCODE_VER%%.*}" -lt 16 ]]; then
            echo "❌ Xcode 16+ required!"
            exit 1
          fi

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Verify Python framework symlink
        run: |
          FRAMEWORK_PATH="/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13"
          if [ ! -x "$FRAMEWORK_PATH" ]; then
            echo "❌ Expected Python 3.13 at $FRAMEWORK_PATH not found!"
            exit 1
          fi
          echo "✅ Python 3.13 found at $FRAMEWORK_PATH"
          

      - name: Prepare Python env
        run: |
          python3.13 --version
          pip3 install --upgrade pip
          pip3 install setuptools
          pip3 install --upgrade setuptools

      - name: Download CloverGnuBuildTools
        run: |
          mkdir -p toolchain/tools/download
          cd toolchain/tools/download
          curl -L -o CloverGnuBuildTools.zip https://github.com/YBronst/CloverBuildUtilities/releases/download/V.1.0/CloverGnuBuildTools.zip
          unzip CloverGnuBuildTools.zip
          cp -r CloverBuildTools/* .
          rm -rf CloverBuildTools CloverGnuBuildTools.zip

      - name: Build CloverBootloader
        run: |
          pwd
          make -C BaseTools "BUILD_CC=clang"
          ./buildme "" ci

      - name: Create DMG with Clover artifacts
        run: |
          cd CloverPackage/sym
          mkdir -p Clover_r5163
          cp Clover_r5163.pkg Clover_r5163.pkg.md5 CloverISO-5163.tar.lzma CloverV2-5163.zip Clover_r5163
          hdiutil create -volname Clover_r5163 -srcfolder Clover_r5163 -ov -format UDZO Clover_r5163.dmg
          mv -f Clover_r5163.dmg CloverPackage/sym/Clover_G_r5163.dmg

      - name: Upload DMG to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Clover_G_r5163.dmg
          path: CloverPackage/sym/Clover_G_r5163.dmg

          
