name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      # Чекаутим репозиторий с полной историей и тегами
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      # Проверка версии Xcode
      - name: Check Xcode version
        run: |
          xcodebuild -version
          XCODE_VER=$(xcodebuild -version | grep Xcode | awk '{print $2}')
          if [[ "${XCODE_VER%%.*}" -lt 16 ]]; then
            echo "❌ Xcode 16+ required!"
            exit 1
          fi

      # Настройка Python 3.13
      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Проверка, что Python 3.13 присутствует в framework
      - name: Verify Python framework symlink
        run: |
          FRAMEWORK_PATH="/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13"
          if [ ! -x "$FRAMEWORK_PATH" ]; then
            echo "❌ Expected Python 3.13 at $FRAMEWORK_PATH not found!"
            exit 1
          fi
          echo "✅ Python 3.13 found at $FRAMEWORK_PATH"

      # Подготовка Python окружения
      - name: Prepare Python env
        run: |
          python3.13 --version
          pip3 install --upgrade pip
          pip3 install setuptools
          pip3 install --upgrade setuptools

      # Сборка BaseTools и запуск buildme
      - name: Build CloverBootloader
        run: |
          cd CloverBootloader/CloverBootloader
          pwd
          ls -la
          make -C BaseTools "BUILD_CC=clang"
          ./buildme "" ci
